//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boats.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoatEquipment
    {
        public int BoatEquipmentID { get; set; }
        public int Boat { get; set; }
        public int Equipment { get; set; }
    
        public virtual AdditionalEquipment AdditionalEquipment { get; set; }
        public virtual Boat Boat1 { get; set; }
    }
}
