//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boats.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int OrderBoat { get; set; }
        public int OrderClient { get; set; }
        public decimal OrderCost { get; set; }
        public bool OrderPrepayment { get; set; }
    
        public virtual Boat Boat { get; set; }
        public virtual Client Client { get; set; }
    }
}
